# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20160521_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
