# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_openinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='monday',
            field=models.ManyToManyField(to='restaurants.OpeningHour'),
        ),
    ]
