# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_monday'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='day',
            field=models.IntegerField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], default=-1),
        ),
    ]
