# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='dishes',
            field=models.ManyToManyField(to='restaurants.Dish'),
        ),
    ]
