# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20160523_1953'),
        ('restaurants', '0011_command_user_tel'),
    ]

    operations = [
    ]
