# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(null=True, verbose_name='nombre')),
                ('plat_commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='plat_commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.NumberDish'),
        ),
    ]
