# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_auto_20160525_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='plat_commande',
        ),
        migrations.AddField(
            model_name='command',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
    ]
