# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_auto_20160525_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='dishes',
            field=models.ManyToManyField(to='restaurants.NumberDish'),
        ),
    ]
