# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_command_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='creation_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='command',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
